import { db } from './index';
import { vocabulary } from './schema';
import 'dotenv/config';

// 1000 kata paling sering digunakan dalam percakapan sehari-hari
const seedVocabulary = [
  // ============================================
  // 1-100: Kata dasar sehari-hari
  // ============================================
    // ============================================
  // 1001-1100: Kata kerja (verbs) tambahan
  // ============================================
  { word: 'achieve', translation: 'mencapai', definition: 'berhasil meraih', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'admire', translation: 'mengagumi', definition: 'memandang dengan kagum', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'adopt', translation: 'mengadopsi', definition: 'mengambil sebagai milik', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'advance', translation: 'maju', definition: 'bergerak ke depan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'afford', translation: 'mampu', definition: 'mempunyai kemampuan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'allow', translation: 'mengizinkan', definition: 'memberi izin', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'announce', translation: 'mengumumkan', definition: 'mengatakan secara resmi', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'apply', translation: 'melamar', definition: 'mengajukan permohonan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'appreciate', translation: 'menghargai', definition: 'mengakui nilai', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'arrange', translation: 'mengatur', definition: 'menyusun', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'avoid', translation: 'menghindari', definition: 'menjauhi', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'base', translation: 'mendasarkan', definition: 'membuat dasar', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'beat', translation: 'mengalahkan', definition: 'menang atas', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'blame', translation: 'menyalahkan', definition: 'menuduh sebagai penyebab', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'bother', translation: 'mengganggu', definition: 'menyusahkan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'breathe', translation: 'bernafas', definition: 'menghirup udara', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'bury', translation: 'mengubur', definition: 'menimbun', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'calculate', translation: 'menghitung', definition: 'melakukan perhitungan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'celebrate', translation: 'merayakan', definition: 'merayakan acara', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'cheat', translation: 'menipu', definition: 'bertindak curang', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'choose', translation: 'memilih', definition: 'menentukan pilihan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'claim', translation: 'mengklaim', definition: 'menyatakan sebagai hak', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'combat', translation: 'melawan', definition: 'bertarung melawan', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'comfort', translation: 'menghibur', definition: 'memberi rasa nyaman', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'commit', translation: 'melakukan', definition: 'melaksanakan', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'compare', translation: 'membandingkan', definition: 'melihat perbedaan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'compete', translation: 'bersaing', definition: 'ikut berlomba', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'complain', translation: 'mengeluh', definition: 'menyatakan ketidakpuasan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'complete', translation: 'menyelesaikan', definition: 'mengakhiri', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'concentrate', translation: 'berkonsentrasi', definition: 'memusatkan perhatian', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'confirm', translation: 'mengkonfirmasi', definition: 'memastikan kebenaran', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'connect', translation: 'menghubungkan', definition: 'membuat hubungan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'control', translation: 'mengendalikan', definition: 'mengawasi', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'convince', translation: 'meyakinkan', definition: 'membuat percaya', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'count', translation: 'menghitung', definition: 'menjumlahkan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'cover', translation: 'menutupi', definition: 'menutup permukaan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'create', translation: 'menciptakan', definition: 'membuat yang baru', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'dare', translation: 'berani', definition: 'mempunyai keberanian', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'decide', translation: 'memutuskan', definition: 'mengambil keputusan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'defeat', translation: 'mengalahkan', definition: 'menang atas musuh', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'defend', translation: 'membela', definition: 'melindungi', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'delay', translation: 'menunda', definition: 'menangguhkan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'deliver', translation: 'mengirimkan', definition: 'menyampaikan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'demand', translation: 'menuntut', definition: 'meminta dengan keras', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'deny', translation: 'menyangkal', definition: 'mengatakan tidak benar', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'depend', translation: 'bergantung', definition: 'memerlukan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'describe', translation: 'menggambarkan', definition: 'menjelaskan rinci', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'deserve', translation: 'layak', definition: 'pantas menerima', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'destroy', translation: 'menghancurkan', definition: 'merusak total', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'develop', translation: 'mengembangkan', definition: 'memajukan', partOfSpeech: 'verb', difficulty: 'intermediate' },

  // ============================================
  // 1101-1200: Kata sifat (adjectives) tambahan
  // ============================================
  { word: 'accurate', translation: 'akurat', definition: 'tepat', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'active', translation: 'aktif', definition: 'sibuk bergerak', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'actual', translation: 'sebenarnya', definition: 'nyata', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'advanced', translation: 'lanjutan', definition: 'tingkat atas', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'ancient', translation: 'kuno', definition: 'sangat tua', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'annual', translation: 'tahunan', definition: 'setiap tahun', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'anxious', translation: 'cemas', definition: 'merasa khawatir', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'appropriate', translation: 'tepat', definition: 'sesuai', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'artificial', translation: 'buatan', definition: 'tidak alami', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'aware', translation: 'sadar', definition: 'mengetahui', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'basic', translation: 'dasar', definition: 'fundamental', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'beneficial', translation: 'bermanfaat', definition: 'memberi keuntungan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'brief', translation: 'singkat', definition: 'pendek', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'broad', translation: 'luas', definition: 'lebar', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'calm', translation: 'tenang', definition: 'tidak gugup', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'capable', translation: 'mampu', definition: 'berkemampuan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'careful', translation: 'hati-hati', definition: 'penuh perhatian', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'casual', translation: 'santai', definition: 'tidak formal', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'central', translation: 'pusat', definition: 'di tengah', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'certain', translation: 'pasti', definition: 'yakin', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'clear', translation: 'jelas', definition: 'mudah dipahami', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'comfortable', translation: 'nyaman', definition: 'memberi kenyamanan', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'common', translation: 'umum', definition: 'sering terjadi', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'complete', translation: 'lengkap', definition: 'utuh', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'complex', translation: 'kompleks', definition: 'rumit', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'confident', translation: 'percaya diri', definition: 'yakin pada diri', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'conscious', translation: 'sadar', definition: 'menyadari', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'constant', translation: 'konstan', definition: 'tetap', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'convenient', translation: 'nyaman', definition: 'mudah digunakan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'correct', translation: 'benar', definition: 'tepat', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'cruel', translation: 'kejam', definition: 'tidak berperikemanusiaan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'curious', translation: 'ingin tahu', definition: 'penasaran', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'dangerous', translation: 'berbahaya', definition: 'membahayakan', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'dark', translation: 'gelap', definition: 'tidak terang', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'dead', translation: 'mati', definition: 'tidak hidup', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'deep', translation: 'dalam', definition: 'jauh ke bawah', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'delicate', translation: 'halus', definition: 'rapuh', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'dense', translation: 'padat', definition: 'rapat', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'desperate', translation: 'putus asa', definition: 'kehilangan harapan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'different', translation: 'berbeda', definition: 'tidak sama', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'direct', translation: 'langsung', definition: 'tanpa perantara', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'dirty', translation: 'kotor', definition: 'tidak bersih', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'double', translation: 'ganda', definition: 'dua kali', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'dramatic', translation: 'dramatis', definition: 'mencolok', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'dry', translation: 'kering', definition: 'tidak basah', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'effective', translation: 'efektif', definition: 'berhasil', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'efficient', translation: 'efisien', definition: 'hemat', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'empty', translation: 'kosong', definition: 'tidak berisi', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'enthusiastic', translation: 'antusias', definition: 'bersemangat', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'essential', translation: 'penting', definition: 'sangat diperlukan', partOfSpeech: 'adjective', difficulty: 'advanced' },

  // ============================================
  // 1201-1300: Kata benda (nouns) tambahan
  // ============================================
  { word: 'ability', translation: 'kemampuan', definition: 'kapasitas', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'absence', translation: 'ketidakhadiran', definition: 'tidak ada', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'abuse', translation: 'penyalahgunaan', definition: 'penggunaan salah', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'access', translation: 'akses', definition: 'kesempatan masuk', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'accident', translation: 'kecelakaan', definition: 'kejadian tak terduga', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'account', translation: 'akun', definition: 'catatan atau rekening', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'achievement', translation: 'pencapaian', definition: 'hasil kerja', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'act', translation: 'tindakan', definition: 'perbuatan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'action', translation: 'aksi', definition: 'kegiatan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'adventure', translation: 'petualangan', definition: 'pengalaman menarik', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'advice', translation: 'nasihat', definition: 'rekomendasi', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'agreement', translation: 'kesepakatan', definition: 'persetujuan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'amount', translation: 'jumlah', definition: 'total', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'analysis', translation: 'analisis', definition: 'pengkajian', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'anger', translation: 'kemarahan', definition: 'perasaan marah', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'animal', translation: 'hewan', definition: 'makhluk hidup', partOfSpeech: 'noun', difficulty: 'beginner' },
  { word: 'appeal', translation: 'daya tarik', definition: 'ketertarikan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'approach', translation: 'pendekatan', definition: 'cara menghadapi', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'area', translation: 'area', definition: 'wilayah', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'aspect', translation: 'aspek', definition: 'sisi', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'assembly', translation: 'perakitan', definition: 'kumpulan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'assessment', translation: 'penilaian', definition: 'evaluasi', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'assumption', translation: 'asumsi', definition: 'anggapan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'atmosphere', translation: 'atmosfer', definition: 'suasana', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'attack', translation: 'serangan', definition: 'penyerangan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'attempt', translation: 'percobaan', definition: 'usaha', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'attitude', translation: 'sikap', definition: 'perilaku', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'attraction', translation: 'daya tarik', definition: 'ketertarikan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'audience', translation: 'penonton', definition: 'orang yang menonton', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'authority', translation: 'otoritas', definition: 'kekuasaan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'balance', translation: 'keseimbangan', definition: 'kesetimbangan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'basis', translation: 'dasar', definition: 'fundamental', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'behavior', translation: 'perilaku', definition: 'tindakan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'belief', translation: 'kepercayaan', definition: 'keyakinan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'belonging', translation: 'kepemilikan', definition: 'milik', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'benefit', translation: 'manfaat', definition: 'keuntungan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'bit', translation: 'sedikit', definition: 'potongan kecil', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'blow', translation: 'pukulan', definition: 'tamparan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'board', translation: 'papan', definition: 'lembaran kayu', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'bond', translation: 'ikatan', definition: 'hubungan kuat', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'border', translation: 'perbatasan', definition: 'batas wilayah', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'boundary', translation: 'batas', definition: 'garis pemisah', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'break', translation: 'istirahat', definition: 'berhenti sejenak', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'breath', translation: 'nafas', definition: 'udara yang dihirup', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'budget', translation: 'anggaran', definition: 'rencana keuangan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'building', translation: 'bangunan', definition: 'gedung', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'bulk', translation: 'sebagian besar', definition: 'mayoritas', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'capacity', translation: 'kapasitas', definition: 'daya tampung', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'care', translation: 'perhatian', definition: 'kepedulian', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'cause', translation: 'penyebab', definition: 'sebab', partOfSpeech: 'noun', difficulty: 'intermediate' },

  // ============================================
  // 1301-1400: Kata kerja lanjutan
  // ============================================
  { word: 'display', translation: 'menampilkan', definition: 'memperlihatkan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'divide', translation: 'membagi', definition: 'memisahkan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'dominate', translation: 'mendominasi', definition: 'menguasai', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'doubt', translation: 'meragukan', definition: 'tidak percaya', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'dress', translation: 'berpakaian', definition: 'memakai baju', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'drop', translation: 'menjatuhkan', definition: 'melepas jatuh', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'educate', translation: 'mendidik', definition: 'memberi pendidikan', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'employ', translation: 'mempekerjakan', definition: 'memberi pekerjaan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'encourage', translation: 'mendorong', definition: 'memberi semangat', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'establish', translation: 'mendirikan', definition: 'membentuk', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'evaluate', translation: 'mengevaluasi', definition: 'menilai', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'expand', translation: 'memperluas', definition: 'melebar', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'explain', translation: 'menjelaskan', definition: 'memberi pengertian', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'explore', translation: 'menjelajah', definition: 'meneliti', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'express', translation: 'mengekspresikan', definition: 'mengungkapkan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'face', translation: 'menghadapi', definition: 'berhadapan dengan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'fix', translation: 'memperbaiki', definition: 'membetulkan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'focus', translation: 'memfokuskan', definition: 'memusatkan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'force', translation: 'memaksa', definition: 'menekan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'form', translation: 'membentuk', definition: 'menciptakan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'gain', translation: 'mendapatkan', definition: 'memperoleh', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'gather', translation: 'mengumpulkan', definition: 'mengumpulkan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'grant', translation: 'memberi', definition: 'menyumbangkan', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'grow', translation: 'tumbuh', definition: 'berkembang', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'handle', translation: 'menangani', definition: 'mengelola', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'harm', translation: 'merugikan', definition: 'menyakiti', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'identify', translation: 'mengidentifikasi', definition: 'mengenali', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'ignore', translation: 'mengabaikan', definition: 'tidak memperhatikan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'illustrate', translation: 'menggambarkan', definition: 'memberi contoh', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'imagine', translation: 'membayangkan', definition: 'berfantasi', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'improve', translation: 'meningkatkan', definition: 'memperbaiki', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'indicate', translation: 'menunjukkan', definition: 'menandakan', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'influence', translation: 'memengaruhi', definition: 'memberi pengaruh', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'inform', translation: 'memberi tahu', definition: 'mengabarkan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'injure', translation: 'melukai', definition: 'menyakiti fisik', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'inspire', translation: 'menginspirasi', definition: 'memberi ide', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'involve', translation: 'melibatkan', definition: 'mencakup', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'isolate', translation: 'mengisolasi', definition: 'memisahkan', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'justify', translation: 'membenarkan', definition: 'memberi alasan', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'label', translation: 'memberi label', definition: 'menamai', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'limit', translation: 'membatasi', definition: 'menentukan batas', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'manage', translation: 'mengelola', definition: 'mengatur', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'mention', translation: 'menyebutkan', definition: 'mengatakan secara singkat', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'modify', translation: 'memodifikasi', definition: 'mengubah', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'monitor', translation: 'memantau', definition: 'mengawasi', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'motivate', translation: 'memotivasi', definition: 'memberi dorongan', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'negotiate', translation: 'bernegosiasi', definition: 'berunding', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'obtain', translation: 'memperoleh', definition: 'mendapat', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'occupy', translation: 'menempati', definition: 'mengisi', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'oppose', translation: 'menentang', definition: 'melawan', partOfSpeech: 'verb', difficulty: 'advanced' },

  // ============================================
  // 1401-1500: Kata sifat lanjutan
  // ============================================
  { word: 'fair', translation: 'adil', definition: 'tidak berat sebelah', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'familiar', translation: 'akrab', definition: 'sudah dikenal', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'fancy', translation: 'mewah', definition: 'berkelas', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'fatal', translation: 'fatal', definition: 'menyebabkan kematian', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'favorite', translation: 'favorit', definition: 'paling disukai', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'federal', translation: 'federal', definition: 'bersifat federal', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'fine', translation: 'baik', definition: 'bagus', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'firm', translation: 'teguh', definition: 'kokoh', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'flexible', translation: 'fleksibel', definition: 'mudah menyesuaikan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'foreign', translation: 'asing', definition: 'dari luar negeri', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'fortunate', translation: 'beruntung', definition: 'mujur', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'free', translation: 'bebas', definition: 'merdeka', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'frequent', translation: 'sering', definition: 'berulang kali', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'fresh', translation: 'segar', definition: 'baru', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'full', translation: 'penuh', definition: 'tidak kosong', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'fun', translation: 'menyenangkan', definition: 'memberi hiburan', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'general', translation: 'umum', definition: 'secara keseluruhan', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'generous', translation: 'dermawan', definition: 'suka memberi', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'gentle', translation: 'lembut', definition: 'halus', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'genuine', translation: 'asli', definition: 'tulen', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'global', translation: 'global', definition: 'mendunia', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'gradual', translation: 'bertahap', definition: 'perlahan-lahan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'grateful', translation: 'bersyukur', definition: 'berterima kasih', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'great', translation: 'hebat', definition: 'luar biasa', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'guilty', translation: 'bersalah', definition: 'menyesal', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'heavy', translation: 'berat', definition: 'mempunyai bobot', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'high', translation: 'tinggi', definition: 'elevasi tinggi', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'huge', translation: 'sangat besar', definition: 'besar sekali', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'identical', translation: 'identik', definition: 'sama persis', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'ignorant', translation: 'bodoh', definition: 'tidak berpengetahuan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'immediate', translation: 'segera', definition: 'tanpa menunggu', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'important', translation: 'penting', definition: 'bernilai', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'impressive', translation: 'mengesankan', definition: 'menakjubkan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'independent', translation: 'mandiri', definition: 'tidak bergantung', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'individual', translation: 'individu', definition: 'perseorangan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'inevitable', translation: 'tak terhindarkan', definition: 'pasti terjadi', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'innocent', translation: 'tidak bersalah', definition: 'suci', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'intense', translation: 'intens', definition: 'sangat kuat', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'interior', translation: 'interior', definition: 'bagian dalam', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'internal', translation: 'internal', definition: 'di dalam', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'joint', translation: 'gabungan', definition: 'bersama', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'junior', translation: 'yuniur', definition: 'lebih muda', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'just', translation: 'adil', definition: 'tidak berat sebelah', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'keen', translation: 'bersemangat', definition: 'antusias', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'key', translation: 'kunci', definition: 'sangat penting', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'large', translation: 'besar', definition: 'berukuran besar', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'leading', translation: 'terkemuka', definition: 'paling utama', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'legal', translation: 'legal', definition: 'sesuai hukum', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'light', translation: 'ringan', definition: 'tidak berat', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'likely', translation: 'mungkin', definition: 'kemungkinan besar', partOfSpeech: 'adjective', difficulty: 'intermediate' },

  // ============================================
  // 1501-1600: Kata benda tambahan
  // ============================================
  { word: 'chance', translation: 'kesempatan', definition: 'peluang', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'change', translation: 'perubahan', definition: 'peralihan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'character', translation: 'karakter', definition: 'watak', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'choice', translation: 'pilihan', definition: 'alternatif', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'circumstance', translation: 'keadaan', definition: 'kondisi', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'claim', translation: 'klaim', definition: 'pernyataan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'climate', translation: 'iklim', definition: 'cuaca rata-rata', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'coast', translation: 'pesisir', definition: 'daerah pantai', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'comment', translation: 'komentar', definition: 'tanggapan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'commitment', translation: 'komitmen', definition: 'janji', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'committee', translation: 'panitia', definition: 'kelompok kerja', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'communication', translation: 'komunikasi', definition: 'pertukaran informasi', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'compassion', translation: 'belas kasih', definition: 'rasa iba', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'competition', translation: 'kompetisi', definition: 'persaingan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'complaint', translation: 'keluhan', definition: 'ketidakpuasan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'complexity', translation: 'kompleksitas', definition: 'kerumitan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'concentrate', translation: 'konsentrasi', definition: 'pemusatan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'concept', translation: 'konsep', definition: 'gagasan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'concern', translation: 'kepedulian', definition: 'perhatian', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'conclusion', translation: 'kesimpulan', definition: 'akhir', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'conduct', translation: 'perilaku', definition: 'tindakan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'conference', translation: 'konferensi', definition: 'pertemuan resmi', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'confidence', translation: 'kepercayaan', definition: 'keyakinan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'conflict', translation: 'konflik', definition: 'pertentangan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'confusion', translation: 'kebingungan', definition: 'kekacauan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'connection', translation: 'koneksi', definition: 'hubungan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'consequence', translation: 'konsekuensi', definition: 'akibat', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'conservation', translation: 'konservasi', definition: 'pelestarian', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'construction', translation: 'konstruksi', definition: 'pembangunan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'consultant', translation: 'konsultan', definition: 'penasihat', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'consumer', translation: 'konsumen', definition: 'pemakai', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'contact', translation: 'kontak', definition: 'hubungan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'container', translation: 'wadah', definition: 'tempat penyimpanan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'contribution', translation: 'kontribusi', definition: 'sumbangan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'conversation', translation: 'percakapan', definition: 'obrolan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'copy', translation: 'salinan', definition: 'duplikat', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'corner', translation: 'sudut', definition: 'pojok', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'corruption', translation: 'korupsi', definition: 'penyalahgunaan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'country', translation: 'negara', definition: 'bangsa', partOfSpeech: 'noun', difficulty: 'beginner' },
  { word: 'courage', translation: 'keberanian', definition: 'kegigihan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'cover', translation: 'sampul', definition: 'penutup', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'culture', translation: 'budaya', definition: 'adat istiadat', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'damage', translation: 'kerusakan', definition: 'kerugian', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'danger', translation: 'bahaya', definition: 'ancaman', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'data', translation: 'data', definition: 'informasi', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'debate', translation: 'debat', definition: 'perdebatan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'debt', translation: 'hutang', definition: 'kewajiban bayar', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'decision', translation: 'keputusan', definition: 'putusan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'defense', translation: 'pertahanan', definition: 'perlindungan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'demand', translation: 'permintaan', definition: 'kebutuhan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'department', translation: 'departemen', definition: 'bagian', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'design', translation: 'desain', definition: 'rancangan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'desire', translation: 'keinginan', definition: 'hasrat', partOfSpeech: 'noun', difficulty: 'intermediate' },

  // ============================================
  // 1601-1700: Kata depan, kata sambung, kata keterangan
  // ============================================
  { word: 'above', translation: 'di atas', definition: 'lebih tinggi', partOfSpeech: 'preposition', difficulty: 'beginner' },
  { word: 'abroad', translation: 'di luar negeri', definition: 'ke negara lain', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'absent', translation: 'tidak hadir', definition: 'tidak ada', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'absolutely', translation: 'mutlak', definition: 'sangat', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'accidentally', translation: 'secara tidak sengaja', definition: 'tanpa rencana', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'accordingly', translation: 'sesuai', definition: 'sebagaimana', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'actually', translation: 'sebenarnya', definition: 'faktanya', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'adequately', translation: 'secukupnya', definition: 'cukup', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'afterward', translation: 'kemudian', definition: 'selanjutnya', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'alone', translation: 'sendiri', definition: 'tanpa teman', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'apart', translation: 'terpisah', definition: 'jauh', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'around', translation: 'sekitar', definition: 'di sekitar', partOfSpeech: 'adverb', difficulty: 'beginner' },
  { word: 'aside', translation: 'samping', definition: 'ke samping', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'automatically', translation: 'otomatis', definition: 'sendiri', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'backward', translation: 'mundur', definition: 'ke belakang', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'basically', translation: 'pada dasarnya', definition: 'intinya', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'briefly', translation: 'singkatnya', definition: 'pendek', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'carefully', translation: 'dengan hati-hati', definition: 'penuh perhatian', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'completely', translation: 'sepenuhnya', definition: 'total', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'constantly', translation: 'terus-menerus', definition: 'selalu', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'continuously', translation: 'terus menerus', definition: 'tanpa henti', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'directly', translation: 'secara langsung', definition: 'tanpa perantara', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'easily', translation: 'dengan mudah', definition: 'tanpa kesulitan', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'elsewhere', translation: 'di tempat lain', definition: 'tempat lain', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'entirely', translation: 'sepenuhnya', definition: 'semua', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'especially', translation: 'terutama', definition: 'khususnya', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'eventually', translation: 'pada akhirnya', definition: 'akhirnya', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'exactly', translation: 'tepat', definition: 'persis', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'finally', translation: 'akhirnya', definition: 'pada akhir', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'formerly', translation: 'sebelumnya', definition: 'dulu', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'frequently', translation: 'sering', definition: 'berulang kali', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'generally', translation: 'umumnya', definition: 'biasanya', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'gradually', translation: 'secara bertahap', definition: 'perlahan', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'hardly', translation: 'hampir tidak', definition: 'nyaris tidak', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'immediately', translation: 'segera', definition: 'tanpa menunda', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'increasingly', translation: 'semakin', definition: 'makin', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'indeed', translation: 'memang', definition: 'benar', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'initially', translation: 'pada awalnya', definition: 'mulanya', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'largely', translation: 'sebagian besar', definition: 'mayoritas', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'lately', translation: 'belakangan', definition: 'akhir-akhir ini', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'lightly', translation: 'ringan', definition: 'tidak keras', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'locally', translation: 'secara lokal', definition: 'di tempat', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'mainly', translation: 'terutama', definition: 'kebanyakan', partOfSpeech: 'adverb', difficulty: 'intermediate' },
  { word: 'naturally', translation: 'secara alami', definition: 'wajar', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'necessarily', translation: 'harus', definition: 'pasti', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'occasionally', translation: 'kadang-kadang', definition: 'sesekali', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'originally', translation: 'awalnya', definition: 'pada mulanya', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'particularly', translation: 'terutama', definition: 'khusus', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'perfectly', translation: 'sempurna', definition: 'ideal', partOfSpeech: 'adverb', difficulty: 'advanced' },
  { word: 'physically', translation: 'secara fisik', definition: 'jasmani', partOfSpeech: 'adverb', difficulty: 'advanced' },

  // ============================================
  // 1701-1800: Kata sifat tambahan
  // ============================================
  { word: 'lively', translation: 'hidup', definition: 'ramai', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'living', translation: 'hidup', definition: 'masih bernafas', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'long', translation: 'panjang', definition: 'ukuran panjang', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'loose', translation: 'longgar', definition: 'tidak ketat', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'loud', translation: 'keras', definition: 'suara tinggi', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'low', translation: 'rendah', definition: 'tidak tinggi', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'lucky', translation: 'beruntung', definition: 'mujur', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'mad', translation: 'gila', definition: 'marah atau tidak waras', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'main', translation: 'utama', definition: 'paling penting', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'major', translation: 'mayor', definition: 'besar', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'marvelous', translation: 'luar biasa', definition: 'menakjubkan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'massive', translation: 'besar sekali', definition: 'sangat besar', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'mature', translation: 'dewasa', definition: 'matang', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'merely', translation: 'hanya', definition: 'sekedar', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'mild', translation: 'ringan', definition: 'tidak parah', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'military', translation: 'militer', definition: 'tentara', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'minimal', translation: 'minimal', definition: 'sangat kecil', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'moderate', translation: 'sedang', definition: 'tidak ekstrim', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'modern', translation: 'modern', definition: 'zaman sekarang', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'modest', translation: 'sederhana', definition: 'tidak berlebihan', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'momentary', translation: 'sesaat', definition: 'sebentar', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'moral', translation: 'moral', definition: 'berkaitan dengan etika', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'mutual', translation: 'saling', definition: 'timbal balik', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'narrow', translation: 'sempit', definition: 'tidak lebar', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'national', translation: 'nasional', definition: 'seluruh negara', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'native', translation: 'asli', definition: 'penduduk asli', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'natural', translation: 'alami', definition: 'alam', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'necessary', translation: 'diperlukan', definition: 'harus ada', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'negative', translation: 'negatif', definition: 'buruk', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'neutral', translation: 'netral', definition: 'tidak memihak', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'nice', translation: 'baik', definition: 'menyenangkan', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'noisy', translation: 'berisik', definition: 'banyak suara', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'normal', translation: 'normal', definition: 'biasa', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'numerous', translation: 'banyak', definition: 'jumlah besar', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'obvious', translation: 'jelas', definition: 'mudah dilihat', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'occasional', translation: 'kadang-kadang', definition: 'sesekali', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'odd', translation: 'aneh', definition: 'tidak biasa', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'official', translation: 'resmi', definition: 'sah', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'only', translation: 'hanya', definition: 'tunggal', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'open', translation: 'terbuka', definition: 'tidak tertutup', partOfSpeech: 'adjective', difficulty: 'beginner' },
  { word: 'operational', translation: 'operasional', definition: 'berfungsi', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'opposite', translation: 'berlawanan', definition: 'terbalik', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'original', translation: 'asli', definition: 'pertama', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'overall', translation: 'keseluruhan', definition: 'secara umum', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'painful', translation: 'menyakitkan', definition: 'membuat sakit', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'partial', translation: 'sebagian', definition: 'tidak seluruhnya', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'particular', translation: 'tertentu', definition: 'khusus', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'passionate', translation: 'bergairah', definition: 'bersemangat', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'passive', translation: 'pasif', definition: 'tidak aktif', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'patient', translation: 'sabar', definition: 'tenang menunggu', partOfSpeech: 'adjective', difficulty: 'advanced' },
  { word: 'peaceful', translation: 'damai', definition: 'tentram', partOfSpeech: 'adjective', difficulty: 'advanced' },

  // ============================================
  // 1801-2000: Kata benda, kata kerja, kata sifat tambahan
  // ============================================
  { word: 'people', translation: 'orang-orang', definition: 'manusia banyak', partOfSpeech: 'noun', difficulty: 'beginner' },
  { word: 'period', translation: 'periode', definition: 'rentang waktu', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'permission', translation: 'izin', definition: 'persetujuan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'personality', translation: 'kepribadian', definition: 'karakter', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'perspective', translation: 'perspektif', definition: 'sudut pandang', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'phase', translation: 'fase', definition: 'tahap', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'phenomenon', translation: 'fenomena', definition: 'gejala', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'philosophy', translation: 'filsafat', definition: 'pemikiran', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'plan', translation: 'rencana', definition: 'strategi', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'policy', translation: 'kebijakan', definition: 'aturan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'politics', translation: 'politik', definition: 'urusan negara', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'pollution', translation: 'polusi', definition: 'pencemaran', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'population', translation: 'populasi', definition: 'jumlah penduduk', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'position', translation: 'posisi', definition: 'tempat', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'positive', translation: 'positif', definition: 'baik', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'possibility', translation: 'kemungkinan', definition: 'peluang', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'poverty', translation: 'kemiskinan', definition: 'kekurangan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'power', translation: 'kekuatan', definition: 'tenaga', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'practice', translation: 'praktik', definition: 'latihan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'presence', translation: 'kehadiran', definition: 'ada', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'president', translation: 'presiden', definition: 'pemimpin negara', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'pressure', translation: 'tekanan', definition: 'dorongan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'prevention', translation: 'pencegahan', definition: 'penghindaran', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'price', translation: 'harga', definition: 'biaya', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'principle', translation: 'prinsip', definition: 'dasar', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'priority', translation: 'prioritas', definition: 'yang utama', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'privilege', translation: 'hak istimewa', definition: 'keistimewaan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'process', translation: 'proses', definition: 'rangkaian', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'production', translation: 'produksi', definition: 'pembuatan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'profession', translation: 'profesi', definition: 'pekerjaan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'profit', translation: 'keuntungan', definition: 'laba', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'progress', translation: 'kemajuan', definition: 'perkembangan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'property', translation: 'properti', definition: 'kepemilikan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'proposal', translation: 'usulan', definition: 'saran', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'protest', translation: 'protes', definition: 'keberatan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'purpose', translation: 'tujuan', definition: 'maksud', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'quality', translation: 'kualitas', definition: 'mutu', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'quantity', translation: 'kuantitas', definition: 'jumlah', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'real', translation: 'nyata', definition: 'benar-benar ada', partOfSpeech: 'adjective', difficulty: 'intermediate' },
  { word: 'reality', translation: 'realitas', definition: 'kenyataan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'reason', translation: 'alasan', definition: 'sebab', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'reform', translation: 'reformasi', definition: 'perubahan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'region', translation: 'wilayah', definition: 'daerah', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'regret', translation: 'penyesalan', definition: 'perasaan menyesal', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'relationship', translation: 'hubungan', definition: 'keterikatan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'religion', translation: 'agama', definition: 'kepercayaan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'reputation', translation: 'reputasi', definition: 'nama baik', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'research', translation: 'penelitian', definition: 'kajian', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'respect', translation: 'respek', definition: 'penghormatan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'responsibility', translation: 'tanggung jawab', definition: 'kewajiban', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'rest', translation: 'istirahat', definition: 'berhenti', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'revolution', translation: 'revolusi', definition: 'perubahan besar', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'risk', translation: 'risiko', definition: 'bahaya', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'role', translation: 'peran', definition: 'tugas', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'routine', translation: 'rutin', definition: 'kebiasaan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'safety', translation: 'keamanan', definition: 'keselamatan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'salary', translation: 'gaji', definition: 'upah', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'satisfaction', translation: 'kepuasan', definition: 'rasa puas', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'scale', translation: 'skala', definition: 'ukuran', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'science', translation: 'ilmu pengetahuan', definition: 'sains', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'security', translation: 'keamanan', definition: 'perlindungan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'sense', translation: 'indra', definition: 'perasaan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'sensitivity', translation: 'sensitivitas', definition: 'kepekaan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'service', translation: 'layanan', definition: 'jasa', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'session', translation: 'sesi', definition: 'pertemuan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'significance', translation: 'signifikansi', definition: 'penting', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'silence', translation: 'keheningan', definition: 'diam', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'situation', translation: 'situasi', definition: 'keadaan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'skill', translation: 'keterampilan', definition: 'keahlian', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'society', translation: 'masyarakat', definition: 'komunitas', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'source', translation: 'sumber', definition: 'asal', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'space', translation: 'ruang', definition: 'tempat', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'speech', translation: 'pidato', definition: 'bicara', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'spirit', translation: 'semangat', definition: 'jiwa', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'spread', translation: 'penyebaran', definition: 'perluasan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'standard', translation: 'standar', definition: 'tolok ukur', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'strategy', translation: 'strategi', definition: 'rencana', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'strength', translation: 'kekuatan', definition: 'daya', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'struggle', translation: 'perjuangan', definition: 'usaha keras', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'student', translation: 'pelajar', definition: 'murid', partOfSpeech: 'noun', difficulty: 'beginner' },
  { word: 'study', translation: 'studi', definition: 'belajar', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'success', translation: 'kesuksesan', definition: 'keberhasilan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'support', translation: 'dukungan', definition: 'bantuan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'surprise', translation: 'kejutan', definition: 'hal tak terduga', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'symbol', translation: 'simbol', definition: 'lambang', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'system', translation: 'sistem', definition: 'tatanan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'taste', translation: 'rasa', definition: 'citarasa', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'technology', translation: 'teknologi', definition: 'ilmu terapan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'temperature', translation: 'suhu', definition: 'derajat panas', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'tension', translation: 'ketegangan', definition: 'tekanan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'theory', translation: 'teori', definition: 'gagasan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'thought', translation: 'pikiran', definition: 'ide', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'threat', translation: 'ancaman', definition: 'bahaya', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'tradition', translation: 'tradisi', definition: 'adat', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'traffic', translation: 'lalu lintas', definition: 'kendaraan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'training', translation: 'pelatihan', definition: 'latihan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'treatment', translation: 'perlakuan', definition: 'tindakan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'trend', translation: 'tren', definition: 'kecenderungan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'trust', translation: 'kepercayaan', definition: 'keyakinan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'truth', translation: 'kebenaran', definition: 'fakta', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'understanding', translation: 'pemahaman', definition: 'pengertian', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'universe', translation: 'alam semesta', definition: 'segala yang ada', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'variety', translation: 'variasi', definition: 'ragam', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'violence', translation: 'kekerasan', definition: 'kekuatan kasar', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'vision', translation: 'visi', definition: 'pandangan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'voice', translation: 'suara', definition: 'bunyi', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'wealth', translation: 'kekayaan', definition: 'harta', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'welfare', translation: 'kesejahteraan', definition: 'kebahagiaan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'wisdom', translation: 'kebijaksanaan', definition: 'pengetahuan dalam', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'worker', translation: 'pekerja', definition: 'karyawan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'writing', translation: 'tulisan', definition: 'karangan', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'youth', translation: 'pemuda', definition: 'masa muda', partOfSpeech: 'noun', difficulty: 'intermediate' },
  { word: 'zone', translation: 'zona', definition: 'kawasan', partOfSpeech: 'noun', difficulty: 'advanced' },
  { word: 'achieve', translation: 'mencapai', definition: 'meraih', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'adapt', translation: 'beradaptasi', definition: 'menyesuaikan', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'adjust', translation: 'menyesuaikan', definition: 'mengatur', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'admire', translation: 'mengagumi', definition: 'memandang kagum', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'adopt', translation: 'mengadopsi', definition: 'mengambil', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'advance', translation: 'maju', definition: 'bergerak', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'afford', translation: 'mampu', definition: 'mempunyai uang', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'announce', translation: 'mengumumkan', definition: 'memberi tahu publik', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'apply', translation: 'melamar', definition: 'mengajukan', partOfSpeech: 'verb', difficulty: 'intermediate' },
  { word: 'appreciate', translation: 'menghargai', definition: 'mengakui', partOfSpeech: 'verb', difficulty: 'advanced' },
  { word: 'arrange', translation: 'mengatur', definition: 'menyusun', partOfSpeech: 'verb', difficulty: 'advanced' },
];

// ============================================
// EKSEKUSI SEED
// ============================================
async function main() {
  console.log(`🌱 Seeding 1000+ vocabulary words...`);
  let inserted = 0;
  for (const item of seedVocabulary) {
    try {
      await db.insert(vocabulary).values(item).onConflictDoNothing();
      inserted++;
    } catch (e) {
      console.error(`❌ Gagal insert "${item.word}":`, e);
    }
  }
  console.log(`✅ Seeding complete! ${inserted} kata berhasil ditambahkan.`);
  process.exit(0);
}

main().catch((e) => {
  console.error('❌ Seed failed:', e);
  process.exit(1);
});